"use node";

import { action } from "../_generated/server";
import { v } from "convex/values";
import { extractBrandFromScreenshot } from "../lib/llm";

function extractHexColor(input: string): string | null {
  const match = input.match(/#([0-9a-fA-F]{3}){1,2}\b/);
  return match ? match[0] : null;
}

function extractLogoUrl(html: string, url: string): string | null {
  const urlObj = new URL(url);
  const base = `${urlObj.protocol}//${urlObj.host}`;

  const patterns = [
    /property=["']og:image["'][^>]*content=["']([^"']+)["']/i,
    /<link[^>]*rel=["'](?:apple-touch-)?icon["'][^>]*href=["']([^"']+)["']/i,
    /<img[^>]*class=["'][^"']*logo[^"']*["'][^>]*src=["']([^"']+)["']/i,
    /<a[^>]*class=["'][^"']*logo[^"']*["'][^>]*href=["']([^"']+)["']/i,
    /data-logo=["']([^"']+)["']/i,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      const logoUrl = match[1];
      if (logoUrl.startsWith("http")) return logoUrl;
      if (logoUrl.startsWith("//")) return `https:${logoUrl}`;
      if (logoUrl.startsWith("/")) return `${base}${logoUrl}`;
    }
  }

  return `${base}/logo.png`;
}

function extractPrimaryColor(html: string): string {
  const patterns = [
    /<meta[^>]*name=["']theme-color["'][^>]*content=["']([^"']+)["']/i,
    /<meta[^>]*property=["']og:theme_color["'][^>]*content=["']([^"']+)["']/i,
    /--primary:\s*(#[0-9a-fA-F]{3,6})/i,
    /--color-primary:\s*(#[0-9a-fA-F]{3,6})/i,
    /color:\s*(#[0-9a-fA-F]{3,6})/i,
    /background-color:\s*(#[0-9a-fA-F]{3,6})/i,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      const color = extractHexColor(match[1]);
      if (color) return color;
    }
  }

  return "#3B82F6";
}

function extractBackgroundColor(html: string): string {
  const patterns = [
    /<meta[^>]*name=["']background-color["'][^>]*content=["']([^"']+)["']/i,
    /--background:\s*(#[0-9a-fA-F]{3,6})/i,
    /--bg:\s*(#[0-9a-fA-F]{3,6})/i,
    /background:\s*#[0-9a-fA-F]{3,6}/i,
    /body[^>]*style=["'][^"']*background(-color)?:\s*([^;"']+)/i,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      const color = extractHexColor(match[1]);
      if (color) return color;
    }
  }

  return "#0F172A";
}

function extractFontFamily(html: string): string {
  const patterns = [
    /font-family:\s*['"]?([^;'"]+)/i,
    /--font:\s*['"]?([^;'"]+)/i,
    /--font-family:\s*['"]?([^;'"]+)/i,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      const font = match[1].trim();
      const commonFonts = ["Inter", "Roboto", "Open Sans", "Lato", "Montserrat", "Poppins", "SF Pro", "system-ui"];
      for (const common of commonFonts) {
        if (font.toLowerCase().includes(common.toLowerCase())) {
          return font;
        }
      }
      return font;
    }
  }

  return "Inter, system-ui, sans-serif";
}

function extractTitle(html: string): string {
  const patterns = [
    /<meta[^>]*property=["']og:title["'][^>]*content=["']([^"']+)["']/i,
    /<title[^>]*>([^<]+)<\/title>/i,
    /<meta[^>]*name=["']title["'][^>]*content=["']([^"']+)["']/i,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      return match[1].trim();
    }
  }

  return "Your Website";
}

function extractDescription(html: string): string {
  const patterns = [
    /<meta[^>]*property=["']og:description["'][^>]*content=["']([^"']+)["']/i,
    /<meta[^>]*name=["']description["'][^>]*content=["']([^"']+)["']/i,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      return match[1].trim().slice(0, 150);
    }
  }

  return "Generated by OGSnap";
}

export const extractFromUrl = action({
  args: {
    url: v.string(),
  },
  handler: async (_ctx, args) => {
    const apiKey = process.env.FIRECRAWL_API_KEY;
    if (!apiKey) {
      return {
        success: false,
        error: "FIRECRAWL_API_KEY is not configured",
      };
    }

    let html = "";
    let title = "Your Website";
    let description = "";
    let screenshotUrl: string | undefined = undefined;

    try {
      const response = await fetch("https://api.firecrawl.dev/v1/scrape", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          url: args.url,
          formats: ["html", "metadata", "screenshot"],
        }),
      });

      if (!response.ok) {
        const details = await response.text();
        return {
          success: false,
          error: `Firecrawl request failed: ${response.status} - ${details.slice(0, 200)}`,
        };
      }

      const payload = (await response.json()) as {
        data?: {
          metadata?: {
            title?: string;
            description?: string;
          };
          html?: string;
          screenshot?: string;
        };
      };

      html = payload.data?.html ?? "";
      title = payload.data?.metadata?.title ?? "Your Website";
      description = payload.data?.metadata?.description ?? "";
      screenshotUrl = payload.data?.screenshot;
    } catch (err) {
      return {
        success: false,
        error: `Failed to fetch URL: ${err instanceof Error ? err.message : "Unknown error"}`,
      };
    }

    if (!html) {
      return {
        success: false,
        error: "No HTML content received from Firecrawl",
      };
    }

    let brandKit: {
      logoUrl?: string;
      primaryColor: string;
      backgroundColor: string;
      fontFamily: string;
      accentColor?: string;
    } | null = null;
    let brandExtractionMethod: "vision" | "regex-fallback" = "regex-fallback";

    if (screenshotUrl) {
      brandKit = await extractBrandFromScreenshot(screenshotUrl);
      if (brandKit) {
        brandExtractionMethod = "vision";
      } else {
        console.warn("Vision-based brand kit extraction failed; falling back to regex.");
      }
    } else {
      console.warn("No screenshot received from Firecrawl; falling back to regex.");
    }

    if (!brandKit) {
      const logoUrl = extractLogoUrl(html, args.url);
      const primaryColor = extractPrimaryColor(html);
      const backgroundColor = extractBackgroundColor(html);
      const fontFamily = extractFontFamily(html);
      brandKit = {
        logoUrl: logoUrl ?? undefined,
        primaryColor,
        backgroundColor,
        fontFamily,
      };
    }

    return {
      success: true,
      result: {
        title: title.slice(0, 100),
        description: description.slice(0, 200),
        logoUrl: brandKit.logoUrl,
        primaryColor: brandKit.primaryColor,
        backgroundColor: brandKit.backgroundColor,
        fontFamily: brandKit.fontFamily,
        accentColor: brandKit.accentColor,
        brandExtractionMethod,
      },
    };
  },
});
